APP:
DATABASE:
FILE:
  SECRETDIR:
    SECRETS: secrets.yml
  SRC:
    DATA:
      RAW_DATA: raw_datas_projet_M5D_Hetic.xlsx
      SHOP_DATA: Magasin_casto.xlsx
      GEO_DATA: correspondance-code-insee-code-postal.json